CREATE TABLE TB_CADASTRO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(255),
    IDADE INT,
    IMG_URL VARCHAR(255),
    NOME VARCHAR(255),
    MISSOES_ID BIGINT
);

CREATE TABLE TB_MISSOES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    DIFICULDADE VARCHAR(255),
    NOME_MISSAO VARCHAR(255)
);
